const PRODUCT_IMAGE_BASE = "/images";

export const products = [
  {
    id: 1,
    name: "Adson Thumb Forcep",
    category: ["CS SETS", "ORTHO SETS"],
    description: "Adson thumb forcep.",
    summary:
      "Fine thumb forceps used for handling dressings, delicate tissues, and sutures during surgical procedures.",
    features: [
      "Fine serrated tips for precision control",
      "Designed for delicate tissue handling",
      "Lightweight ergonomic profile",
      "Autoclavable stainless steel construction",
    ],
    image: `${PRODUCT_IMAGE_BASE}/products/adson-thumb-forcep.png`,
    status: "Available",
  },
  {
    id: 2,
    name: "Adson Tissue Forcep",
    category: ["CS SETS", "ORTHO SETS"],
    description: "Adson tissue forcep.",
    summary:
      "Tissue forceps with interlocking teeth for secure grasping of skin and soft tissue during surgery.",
    features: [
      "1x2 toothed tip design",
      "Secure tissue fixation",
      "Precision surgical control",
      "Corrosion-resistant stainless steel",
    ],
    image: `${PRODUCT_IMAGE_BASE}/products/adson-tissue-forcep.png`,
    status: "Available",
  },
  {
    id: 3,
    name: "Allis 6",
    category: ["CS SETS", "ORTHO SETS", "NEW SETS"],
    description: "Allis forceps size 6.",
    summary:
      "6-inch Allis tissue forceps designed for grasping and holding fascia, tendons, and soft tissue during surgical procedures.",
    features: [
      "Interlocking teeth for secure tissue grasping",
      "Ratchet locking mechanism",
      "Ideal for fascia and soft tissue traction",
      "Medical-grade stainless steel construction",
    ],
    image: `${PRODUCT_IMAGE_BASE}/products/allis-6.png`,
    status: "Available",
  },
  {
    id: 4,
    name: "Allis 8",
    category: ["CS SETS", "ORTHO SETS"],
    description: "Allis forceps size 8.",
    summary:
      "8-inch Allis forceps offering deeper surgical reach for holding and retracting tissue.",
    features: [
      "Extended length design",
      "Interlocking tissue-holding teeth",
      "Locking ratchet handle",
      "Reusable surgical-grade steel",
    ],
    image: `${PRODUCT_IMAGE_BASE}/products/allis-8.png`,
    status: "Available",
  },
  {
    id: 5,
    name: "Amniotom",
    category: ["CS SETS", "ORTHO SETS"],
    description: "Amniotomy instrument.",
    summary:
      "Specialized obstetric instrument used for controlled artificial rupture of amniotic membranes during labor.",
    features: [
      "Precision hook tip",
      "Designed for amniotomy procedures",
      "Controlled membrane puncture",
      "Smooth ergonomic handle",
    ],
    image: `${PRODUCT_IMAGE_BASE}/products/amniotom.png`,
    status: "Available",
  },
  {
    id: 6,
    name: "Anal Retractor",
    category: ["CS SETS", "ORTHO SETS"],
    description: "Anal retractor.",
    summary:
      "Retractor designed to expose the anal canal and rectal region during examination and surgical procedures.",
    features: [
      "Enhanced operative visibility",
      "Atraumatic tissue retraction",
      "Durable stainless steel build",
      "Easy manual operation",
    ],
    image: `${PRODUCT_IMAGE_BASE}/products/anal-retractor.png`,
    status: "Available",
  },
  {
    id: 7,
    name: "Anal Speculum",
    category: ["CS SETS", "ORTHO SETS"],
    description: "Anal speculum.",
    summary:
      "Diagnostic and surgical instrument used for visualization of the anal canal and lower rectum.",
    features: [
      "Provides clear visualization",
      "Adjustable opening mechanism",
      "Smooth atraumatic edges",
      "Reusable stainless steel construction",
    ],
    image: `${PRODUCT_IMAGE_BASE}/products/anal-speculum.png`,
    status: "Available",
  },
  {
    id: 8,
    name: "Army Navy Small",
    category: ["CS SETS", "ORTHO SETS"],
    description: "Army-Navy retractor (small).",
    summary:
      "Compact double-ended retractor used for retracting superficial tissues in minor surgical procedures.",
    features: [
      "Dual-ended blade design",
      "Compact surgical profile",
      "Versatile tissue retraction",
      "Autoclavable stainless steel",
    ],
    image: `${PRODUCT_IMAGE_BASE}/products/army-navy-small.png`,
    status: "Available",
  },
  {
    id: 9,
    name: "Army Navy",
    category: ["CS SETS", "ORTHO SETS"],
    description: "Army-Navy retractor.",
    summary:
      "General-purpose double-ended retractor used to maintain exposure of surgical sites.",
    features: [
      "Dual blade retraction",
      "Suitable for various procedures",
      "Balanced ergonomic design",
      "Reusable surgical-grade steel",
    ],
    image: `${PRODUCT_IMAGE_BASE}/products/army-navy.png`,
    status: "Available",
  },
  {
    id: 10,
    name: "Artery Forceps St",
    category: ["CS SETS", "ORTHO SETS"],
    description: "Artery forceps (st).",
    summary:
      "Straight hemostatic forceps used to clamp blood vessels and control bleeding during surgery.",
    features: [
      "Straight serrated jaws",
      "Ratchet locking system",
      "Reliable hemostatic control",
      "Corrosion-resistant construction",
    ],
    image: `${PRODUCT_IMAGE_BASE}/products/artery-forceps-st.png`,
    status: "Available",
  },
  {
    id: 11,
    name: "Babcock 6",
    category: ["CS SETS", "ORTHO SETS"],
    description: "Babcock forceps size 6.",
    summary:
      "6-inch atraumatic forceps used for grasping delicate tubular structures such as bowel and fallopian tubes.",
    features: [
      "Fenestrated jaws",
      "Non-crushing tissue handling",
      "Ratchet locking mechanism",
      "Precision surgical control",
    ],
    image: `${PRODUCT_IMAGE_BASE}/products/babcock-6.png`,
    status: "Available",
  },
  {
    id: 12,
    name: "Babcock 8",
    category: ["CS SETS", "ORTHO SETS"],
    description: "Babcock forceps size 8.",
    summary:
      "8-inch Babcock forceps providing extended reach for atraumatic tissue handling.",
    features: [
      "Extended length access",
      "Fenestrated atraumatic jaws",
      "Secure tissue retention",
      "Medical-grade stainless steel",
    ],
    image: `${PRODUCT_IMAGE_BASE}/products/babcock-8.png`,
    status: "Available",
  },
  {
    id: 13,
    name: "Baby Richardson",
    category: ["CS SETS", "ORTHO SETS"],
    description: "Baby Richardson retractor.",
    summary:
      "Small Richardson retractor used for shallow wound exposure and delicate tissue retraction.",
    features: [
      "Compact blade size",
      "Excellent surgical visibility",
      "Smooth tissue handling",
      "Reusable stainless steel",
    ],
    image: `${PRODUCT_IMAGE_BASE}/products/baby-richardson.png`,
    status: "Available",
  },
  {
    id: 14,
    name: "Balfour",
    category: ["CS SETS", "ORTHO SETS"],
    description: "Balfour retractor (self retaining).",
    summary:
      "Self-retaining abdominal retractor commonly used to maintain exposure during open abdominal surgery.",
    features: [
      "Self-retaining frame",
      "Adjustable side blades",
      "Wide abdominal exposure",
      "Heavy-duty surgical construction",
    ],
    image: `${PRODUCT_IMAGE_BASE}/products/balfour.png`,
    status: "Available",
  },
  {
    id: 15,
    name: "Bandage Scissors",
    category: ["CS SETS", "ORTHO SETS"],
    description: "Bandage scissors.",
    summary:
      "Safety scissors designed for quick and safe removal of bandages, dressings, and medical tape.",
    features: [
      "Blunt lower safety tip",
      "Sharp cutting edge",
      "Reduces risk of skin injury",
      "Durable stainless steel",
    ],
    image: `${PRODUCT_IMAGE_BASE}/products/bandage-scissors.png`,
    status: "Available",
  },
  {
    id: 16,
    name: "Bayonet Nasal Forcep",
    category: ["CS SETS", "ORTHO SETS"],
    description: "Bayonet nasal forcep.",
    summary:
      "ENT forceps with a bayonet profile allowing unobstructed visibility during nasal procedures.",
    features: [
      "Offset bayonet design",
      "Improved surgical visibility",
      "Precision gripping tips",
      "Ideal for ENT applications",
    ],
    image: `${PRODUCT_IMAGE_BASE}/products/bayonet-nasal-forcep.png`,
    status: "Available",
  },
  {
    id: 17,
    name: "Bladder Retractor",
    category: ["CS SETS", "ORTHO SETS"],
    description: "Bladder retractor.",
    summary:
      "Specialized retractor used to retract and protect the bladder during pelvic and gynecological procedures.",
    features: [
      "Broad protective blade",
      "Enhanced pelvic exposure",
      "Atraumatic tissue retraction",
      "Reusable stainless steel",
    ],
    image: `${PRODUCT_IMAGE_BASE}/products/bladder-retractor.png`,
    status: "Available",
  },
  {
    id: 18,
    name: "Blade Holder 3",
    category: ["CS SETS", "ORTHO SETS"],
    description: "Blade holder size 3.",
    summary:
      "Scalpel handle designed for use with smaller surgical blades for precision incisions.",
    features: [
      "Compatible with blades #10–15",
      "Secure blade mounting",
      "Textured grip surface",
      "Autoclavable design",
    ],
    image: `${PRODUCT_IMAGE_BASE}/products/blade-holder-3.png`,
    status: "Available",
  },
  {
    id: 19,
    name: "Blade Holder 4",
    category: ["CS SETS", "ORTHO SETS"],
    description: "Blade holder size 4.",
    summary:
      "Large scalpel handle used with major surgical blades for deeper and longer incisions.",
    features: [
      "Compatible with blades #20–24",
      "Secure blade attachment",
      "Balanced handling",
      "Reusable stainless steel",
    ],
    image: `${PRODUCT_IMAGE_BASE}/products/blade-holder-4.png`,
    status: "Available",
  },
  {
    id: 20,
    name: "Bone Aspirator",
    category: ["CS SETS", "ORTHO SETS"],
    description: "Bone aspirator.",
    summary:
      "Orthopedic suction instrument used to remove blood, fluids, and debris from bone operative sites.",
    features: [
      "Efficient fluid evacuation",
      "Precision suction control",
      "Orthopedic surgical application",
      "Autoclavable construction",
    ],
    image: `${PRODUCT_IMAGE_BASE}/products/bone-aspirator.png`,
    status: "Available",
  },
  {
    id: 21,
    name: "Bone Chisel Osteotome",
    category: ["CS SETS", "ORTHO SETS"],
    description: "Bone chisel / osteotome.",
    summary:
      "Orthopedic cutting instrument used for shaping, cutting, and removing bone tissue.",
    features: [
      "Sharp beveled edge",
      "Suitable for osteotomy procedures",
      "Impact-resistant design",
      "Surgical-grade stainless steel",
    ],
    image: `${PRODUCT_IMAGE_BASE}/products/bone-chisel-osteotome.png`,
    status: "Available",
  },
  {
    id: 22,
    name: "Bone Clamp",
    category: ["CS SETS", "ORTHO SETS"],
    description: "Bone clamp.",
    summary:
      "Orthopedic clamp used to stabilize and align bone fragments during fixation procedures.",
    features: [
      "Strong clamping force",
      "Secure bone stabilization",
      "Precision alignment assistance",
      "Heavy-duty construction",
    ],
    image: `${PRODUCT_IMAGE_BASE}/products/bone-clamp.png`,
    status: "Available",
  },
  {
    id: 23,
    name: "Bone Curette",
    category: ["CS SETS", "ORTHO SETS"],
    description: "Bone curette.",
    summary:
      "Spoon-shaped orthopedic instrument used for bone debridement and removal of pathological tissue.",
    features: [
      "Sharp curette cup",
      "Controlled tissue removal",
      "Orthopedic surgical use",
      "Reusable stainless steel",
    ],
    image: `${PRODUCT_IMAGE_BASE}/products/bone-curette.png`,
    status: "Available",
  },
  {
    id: 24,
    name: "Bone Cutter",
    category: ["CS SETS", "ORTHO SETS"],
    description: "Bone cutter.",
    summary:
      "Heavy-duty orthopedic instrument designed for cutting and trimming bone structures.",
    features: [
      "High-strength cutting jaws",
      "Excellent leverage",
      "Orthopedic-grade performance",
      "Corrosion-resistant steel",
    ],
    image: `${PRODUCT_IMAGE_BASE}/products/bone-cutter.png`,
    status: "Available",
  },
  {
    id: 25,
    name: "Bone Drill",
    category: ["CS SETS", "ORTHO SETS"],
    description: "Bone drill.",
    summary:
      "Orthopedic drilling instrument used to create precise holes in bone for fixation and implant procedures.",
    features: [
      "Accurate drilling capability",
      "Supports fixation procedures",
      "Durable orthopedic construction",
      "Reusable surgical instrument",
    ],
    image: `${PRODUCT_IMAGE_BASE}/products/bone-drill.png`,
    status: "Available",
  },
  {
    id: 26,
    name: "Bone File",
    category: ["CS SETS", "ORTHO SETS"],
    description: "Bone file.",
    summary:
      "Orthopedic instrument used for smoothing, shaping, and finishing bone surfaces after cutting procedures.",
    features: [
      "Precision filing surface",
      "Smooth bone contouring",
      "Durable orthopedic-grade construction",
      "Reusable stainless steel",
    ],
    image: `${PRODUCT_IMAGE_BASE}/products/bone-file.png`,
    status: "Available",
  },
  {
    id: 27,
    name: "Bone Holder Big",
    category: ["CS SETS", "ORTHO SETS"],
    description: "Large bone holder.",
    summary:
      "Large orthopedic forceps designed to securely grasp and stabilize larger bone fragments during surgery.",
    features: [
      "Heavy-duty gripping jaws",
      "Secure bone stabilization",
      "Large-size orthopedic design",
      "Ratchet locking mechanism",
    ],
    image: `${PRODUCT_IMAGE_BASE}/products/bone-holder-big.png`,
    status: "Available",
  },
  {
    id: 28,
    name: "Bone Holder Small",
    category: ["CS SETS", "ORTHO SETS"],
    description: "Small bone holder.",
    summary:
      "Compact orthopedic holder used for precise stabilization of smaller bone fragments.",
    features: [
      "Precision gripping jaws",
      "Ideal for smaller bones",
      "Secure locking mechanism",
      "Stainless steel construction",
    ],
    image: `${PRODUCT_IMAGE_BASE}/products/bone-holder-small.png`,
    status: "Available",
  },
  {
    id: 29,
    name: "Bone Mallet",
    category: ["CS SETS", "ORTHO SETS"],
    description: "Bone mallet.",
    summary:
      "Orthopedic mallet used to strike osteotomes, chisels, and other bone instruments during procedures.",
    features: [
      "Balanced surgical weight",
      "Impact-resistant head",
      "Orthopedic surgical application",
      "Durable construction",
    ],
    image: `${PRODUCT_IMAGE_BASE}/products/bone-mallet.png`,
    status: "Available",
  },
  {
    id: 30,
    name: "Bone Rangeur Cu",
    category: ["CS SETS", "ORTHO SETS"],
    description: "Bone rangeur (cu).",
    summary:
      "Curved bone rongeur used for removing and contouring bone during orthopedic procedures.",
    features: [
      "Curved cutting jaws",
      "Controlled bone removal",
      "Strong cutting action",
      "Reusable surgical steel",
    ],
    image: `${PRODUCT_IMAGE_BASE}/products/bone-rangeur-cu.png`,
    status: "Available",
  },
  {
    id: 31,
    name: "Bone Rangeur St",
    category: ["CS SETS", "ORTHO SETS"],
    description: "Bone rangeur (st).",
    summary:
      "Straight bone rongeur designed for precise removal of bone and hard tissue.",
    features: [
      "Straight cutting jaws",
      "Controlled bone excision",
      "High-strength construction",
      "Orthopedic-grade design",
    ],
    image: `${PRODUCT_IMAGE_BASE}/products/bone-rangeur-st.png`,
    status: "Available",
  },
  {
    id: 32,
    name: "Bone Saw Ortho",
    category: ["CS SETS", "ORTHO SETS"],
    description: "Orthopedic bone saw.",
    summary:
      "Orthopedic hand saw used for cutting bone during trauma and reconstructive procedures.",
    features: [
      "Sharp serrated blade",
      "Efficient bone cutting",
      "Ergonomic handle",
      "Durable surgical construction",
    ],
    image: `${PRODUCT_IMAGE_BASE}/products/bone-saw-ortho.png`,
    status: "Available",
  },
  {
    id: 33,
    name: "Bone Skid",
    category: ["CS SETS", "ORTHO SETS"],
    description: "Bone skid.",
    summary:
      "Orthopedic instrument used to protect soft tissue while manipulating or elevating bone structures.",
    features: [
      "Smooth protective surface",
      "Tissue protection during surgery",
      "Precision orthopedic use",
      "Reusable stainless steel",
    ],
    image: `${PRODUCT_IMAGE_BASE}/products/bone-skid.png`,
    status: "Available",
  },
  {
    id: 34,
    name: "Bulldogs",
    category: ["CS SETS", "ORTHO SETS"],
    description: "Bulldog clamps.",
    summary:
      "Spring-loaded vascular clamps used for temporary occlusion of blood vessels during surgery.",
    features: [
      "Atraumatic vascular clamping",
      "Spring-loaded mechanism",
      "Reliable vessel occlusion",
      "Available for delicate procedures",
    ],
    image: `${PRODUCT_IMAGE_BASE}/products/bulldogs.png`,
    status: "Available",
  },
  {
    id: 35,
    name: "Cast Spreader",
    category: ["CS SETS", "ORTHO SETS"],
    description: "Cast spreader.",
    summary:
      "Orthopedic instrument used to spread and remove plaster or fiberglass casts safely.",
    features: [
      "Controlled spreading action",
      "Heavy-duty jaws",
      "Ideal for cast removal",
      "Durable stainless steel",
    ],
    image: `${PRODUCT_IMAGE_BASE}/products/cast-spreader.png`,
    status: "Available",
  },
  {
    id: 36,
    name: "CDB Dilators",
    category: ["CS SETS", "ORTHO SETS"],
    description: "CDB dilators.",
    summary:
      "Graduated dilators used for controlled enlargement of anatomical passages during procedures.",
    features: [
      "Graduated sizing",
      "Smooth insertion profile",
      "Reusable instrument set",
      "Medical-grade finish",
    ],
    image: `${PRODUCT_IMAGE_BASE}/products/cdb-dilators.png`,
    status: "Available",
  },
  {
    id: 37,
    name: "Cervical Punch Biopsy",
    category: ["CS SETS", "ORTHO SETS"],
    description: "Cervical punch biopsy instrument.",
    summary:
      "Gynecological instrument designed for obtaining cervical tissue samples for diagnostic evaluation.",
    features: [
      "Sharp biopsy jaws",
      "Precise tissue sampling",
      "Minimal tissue trauma",
      "Stainless steel construction",
    ],
    image: `${PRODUCT_IMAGE_BASE}/products/cervical-punch-biopsy.png`,
    status: "Available",
  },
  {
    id: 38,
    name: "Chavalier Tube",
    category: ["CS SETS", "ORTHO SETS"],
    description: "Chavalier tube.",
    summary:
      "Tracheostomy tube component used to maintain airway patency following tracheal procedures.",
    features: [
      "Airway maintenance support",
      "Smooth tube profile",
      "Reliable surgical application",
      "Medical-grade construction",
    ],
    image: `${PRODUCT_IMAGE_BASE}/products/chavalier-tube.png`,
    status: "Available",
  },
  {
    id: 39,
    name: "Chisel",
    category: ["CS SETS", "ORTHO SETS"],
    description: "Chisel.",
    summary:
      "Surgical chisel used for cutting, shaping, and removing bone during orthopedic procedures.",
    features: [
      "Sharp beveled blade",
      "Impact-resistant design",
      "Controlled bone shaping",
      "Orthopedic-grade steel",
    ],
    image: `${PRODUCT_IMAGE_BASE}/products/chisel.png`,
    status: "Available",
  },
  {
    id: 40,
    name: "Deaver Retractor Narrow 2",
    category: ["CS SETS", "ORTHO SETS"],
    description: "Deaver retractor (narrow 2).",
    summary:
      "Narrow curved Deaver retractor designed for deep tissue and organ retraction.",
    features: [
      "Curved blade profile",
      "Deep cavity exposure",
      "Atraumatic tissue handling",
      "Stainless steel construction",
    ],
    image: `${PRODUCT_IMAGE_BASE}/products/deaver-retractor-narrow-2.png`,
    status: "Available",
  },
  {
    id: 41,
    name: "Deaver Retractor Narrow 3",
    category: ["CS SETS", "ORTHO SETS"],
    description: "Deaver retractor (narrow 3).",
    summary:
      "Extended narrow Deaver retractor providing enhanced access to deep surgical fields.",
    features: [
      "Long curved blade",
      "Improved deep retraction",
      "Smooth atraumatic edges",
      "Reusable surgical steel",
    ],
    image: `${PRODUCT_IMAGE_BASE}/products/deaver-retractor-narrow-3.png`,
    status: "Available",
  },
  {
    id: 42,
    name: "Deaver Retractors Per Size",
    category: ["CS SETS", "ORTHO SETS"],
    description: "Deaver retractors per size.",
    summary:
      "Collection of Deaver retractors available in multiple blade widths for varying surgical needs.",
    features: [
      "Multiple size options",
      "Deep tissue retraction",
      "Curved blade design",
      "Surgical-grade stainless steel",
    ],
    image: `${PRODUCT_IMAGE_BASE}/products/deaver-retractors-per-size.png`,
    status: "Available",
  },
  {
    id: 43,
    name: "Dissecting Probe",
    category: ["CS SETS", "ORTHO SETS"],
    description: "Dissecting probe.",
    summary:
      "Fine probe used for exploring, separating, and identifying anatomical structures during surgery.",
    features: [
      "Fine precision tip",
      "Tactile surgical feedback",
      "Delicate tissue manipulation",
      "Reusable construction",
    ],
    image: `${PRODUCT_IMAGE_BASE}/products/dissecting-probe.png`,
    status: "Available",
  },
  {
    id: 44,
    name: "Dissecting Scissors",
    category: ["CS SETS", "ORTHO SETS"],
    description: "Dissecting scissors.",
    summary:
      "Precision scissors designed for sharp and blunt tissue dissection during surgical procedures.",
    features: [
      "Fine cutting blades",
      "Controlled dissection",
      "Smooth cutting action",
      "Medical-grade stainless steel",
    ],
    image: `${PRODUCT_IMAGE_BASE}/products/dissecting-scissors.png`,
    status: "Available",
  },
  {
    id: 45,
    name: "Dull Curette",
    category: ["CS SETS", "ORTHO SETS"],
    description: "Dull curette.",
    summary:
      "Curette with a blunt working end used for gentle scraping and tissue removal.",
    features: [
      "Blunt curette tip",
      "Controlled tissue removal",
      "Reduced tissue trauma",
      "Reusable stainless steel",
    ],
    image: `${PRODUCT_IMAGE_BASE}/products/dull-curette.png`,
    status: "Available",
  },
  {
    id: 46,
    name: "Fistula Probe",
    category: ["CS SETS", "ORTHO SETS"],
    description: "Fistula probe.",
    summary:
      "Probe used for locating, examining, and assessing fistulous tracts during surgery.",
    features: [
      "Smooth rounded tip",
      "Easy tract exploration",
      "Enhanced procedural accuracy",
      "Corrosion-resistant steel",
    ],
    image: `${PRODUCT_IMAGE_BASE}/products/fistula-probe.png`,
    status: "Available",
  },
  {
    id: 47,
    name: "Gigli Wire C Handle",
    category: ["CS SETS", "ORTHO SETS"],
    description: "Gigli wire with C-handle.",
    summary:
      "Orthopedic wire saw system with handles used for controlled bone cutting procedures.",
    features: [
      "Comfortable C-handle grip",
      "Compatible with Gigli wire",
      "Controlled bone sawing",
      "Orthopedic surgical use",
    ],
    image: `${PRODUCT_IMAGE_BASE}/products/gigli-wire-c-handle.png`,
    status: "Available",
  },
  {
    id: 48,
    name: "Gigli Wire",
    category: ["CS SETS", "ORTHO SETS"],
    description: "Gigli wire.",
    summary:
      "Flexible wire saw used in orthopedic and neurosurgical procedures for bone cutting.",
    features: [
      "Flexible wire design",
      "Efficient bone cutting",
      "Compatible with Gigli handles",
      "Precision orthopedic application",
    ],
    image: `${PRODUCT_IMAGE_BASE}/products/gigli-wire.png`,
    status: "Available",
  },
  {
    id: 49,
    name: "Goodells Dilator",
    category: ["CS SETS", "ORTHO SETS"],
    description: "Goodell's dilator.",
    summary:
      "Gynecological dilator used for gradual cervical dilation during diagnostic and therapeutic procedures.",
    features: [
      "Double-ended design",
      "Graduated dilation sizes",
      "Smooth atraumatic insertion",
      "Reusable stainless steel",
    ],
    image: `${PRODUCT_IMAGE_BASE}/products/goodells-dilator.png`,
    status: "Available",
  },
  {
    id: 50,
    name: "Hegar Dilator",
    category: ["CS SETS", "ORTHO SETS"],
    description: "Hegar dilator.",
    summary:
      "Cylindrical gynecological dilator used for progressive cervical dilation during procedures.",
    features: [
      "Graduated diameter sizing",
      "Smooth polished finish",
      "Accurate cervical dilation",
      "Medical-grade stainless steel",
    ],
    image: `${PRODUCT_IMAGE_BASE}/products/hegar-dilator.png`,
    status: "Available",
  },
  {
    id: 51,
    name: "Hemorrhoidal Clamp",
    category: ["CS SETS", "ORTHO SETS"],
    description: "Hemorrhoidal clamp.",
    summary:
      "Specialized clamp used during hemorrhoidectomy procedures to securely grasp hemorrhoidal tissue.",
    features: [
      "Strong tissue-holding jaws",
      "Secure ratchet locking mechanism",
      "Designed for anorectal procedures",
      "Reusable stainless steel construction",
    ],
    image: `${PRODUCT_IMAGE_BASE}/products/hemorrhoidal-clamp.png`,
    status: "Available",
  },
  {
    id: 52,
    name: "Hohmann Retractor",
    category: ["CS SETS", "ORTHO SETS"],
    description: "Hohmann retractor.",
    summary:
      "Orthopedic retractor used for exposing bone surfaces and retracting soft tissue during surgery.",
    features: [
      "Flat blade with curved tip",
      "Excellent bone exposure",
      "Orthopedic surgical application",
      "Durable stainless steel",
    ],
    image: `${PRODUCT_IMAGE_BASE}/products/hohmann-retractor.png`,
    status: "Available",
  },
  {
    id: 53,
    name: "Hysterometer",
    category: ["CS SETS", "ORTHO SETS"],
    description: "Hysterometer.",
    summary:
      "Gynecological measuring instrument used to determine uterine depth before intrauterine procedures.",
    features: [
      "Graduated measurement markings",
      "Smooth atraumatic tip",
      "Accurate uterine assessment",
      "Reusable stainless steel",
    ],
    image: `${PRODUCT_IMAGE_BASE}/products/hysterometer.png`,
    status: "Available",
  },
  {
    id: 54,
    name: "Intestinal Clamp Cu",
    category: ["CS SETS", "ORTHO SETS"],
    description: "Intestinal clamp (cu).",
    summary:
      "Curved intestinal clamp used to temporarily occlude bowel segments during gastrointestinal surgery.",
    features: [
      "Curved atraumatic jaws",
      "Even pressure distribution",
      "Secure bowel occlusion",
      "Ratchet locking mechanism",
    ],
    image: `${PRODUCT_IMAGE_BASE}/products/intestinal-clamp-cu.png`,
    status: "Available",
  },
  {
    id: 55,
    name: "Intestinal Clamp St",
    category: ["CS SETS", "ORTHO SETS"],
    description: "Intestinal clamp (st).",
    summary:
      "Straight intestinal clamp designed for atraumatic bowel handling and temporary occlusion.",
    features: [
      "Straight serrated jaws",
      "Non-crushing tissue control",
      "Reliable locking system",
      "Surgical-grade stainless steel",
    ],
    image: `${PRODUCT_IMAGE_BASE}/products/intestinal-clamp-st.png`,
    status: "Available",
  },
  {
    id: 56,
    name: "Iris Scissor Curved",
    category: ["CS SETS", "ORTHO SETS"],
    description: "Iris scissor (curved).",
    summary:
      "Fine curved scissors used for delicate tissue dissection in ophthalmic and microsurgical procedures.",
    features: [
      "Sharp curved blades",
      "Precision cutting performance",
      "Ideal for delicate tissues",
      "Lightweight surgical design",
    ],
    image: `${PRODUCT_IMAGE_BASE}/products/iris-scissor-curved.png`,
    status: "Available",
  },
  {
    id: 57,
    name: "Iris Scissor Straight",
    category: ["CS SETS", "ORTHO SETS"],
    description: "Iris scissor (straight).",
    summary:
      "Fine straight scissors designed for precise cutting of delicate tissues and sutures.",
    features: [
      "Straight precision blades",
      "Fine-tip control",
      "Suitable for microsurgery",
      "Reusable stainless steel",
    ],
    image: `${PRODUCT_IMAGE_BASE}/products/iris-scissor-straight.png`,
    status: "Available",
  },
  {
    id: 58,
    name: "Jacson Tracheal Hook",
    category: ["CS SETS", "ORTHO SETS"],
    description: "Jacson tracheal hook.",
    summary:
      "Tracheal hook used to stabilize and elevate the trachea during tracheostomy procedures.",
    features: [
      "Sharp precision hook",
      "Enhanced tracheal exposure",
      "Secure tissue control",
      "Medical-grade stainless steel",
    ],
    image: `${PRODUCT_IMAGE_BASE}/products/jacson-tracheal-hook.png`,
    status: "Available",
  },
  {
    id: 59,
    name: "Kelly Curved 6",
    category: ["CS SETS", "ORTHO SETS"],
    description: "Kelly curved 6.",
    summary:
      "Curved Kelly hemostatic forceps used for clamping vessels and blunt tissue dissection.",
    features: [
      "Curved serrated jaws",
      "Ratchet locking mechanism",
      "Versatile surgical application",
      "Corrosion-resistant steel",
    ],
    image: `${PRODUCT_IMAGE_BASE}/products/kelly-curved-6.png`,
    status: "Available",
  },
  {
    id: 60,
    name: "Kelly Straight 6",
    category: ["CS SETS", "ORTHO SETS"],
    description: "Kelly straight 6.",
    summary:
      "Straight Kelly forceps designed for vessel clamping and tissue handling during surgery.",
    features: [
      "Straight serrated jaws",
      "Reliable hemostatic control",
      "Secure locking ratchet",
      "Reusable surgical-grade steel",
    ],
    image: `${PRODUCT_IMAGE_BASE}/products/kelly-straight-6.png`,
    status: "Available",
  },
  {
    id: 61,
    name: "Kocher Retractor",
    category: ["CS SETS", "ORTHO SETS"],
    description: "Kocher retractor.",
    summary:
      "Handheld retractor used to provide exposure and maintain visibility during surgical procedures.",
    features: [
      "Strong retraction capability",
      "Ergonomic handle design",
      "Excellent wound exposure",
      "Durable stainless steel construction",
    ],
    image: `${PRODUCT_IMAGE_BASE}/products/kocher-retractor.png`,
    status: "Available",
  },
  {
    id: 62,
    name: "Ligature Needle",
    category: ["CS SETS", "ORTHO SETS"],
    description: "Ligature needle.",
    summary:
      "Specialized needle used for passing ligatures around vessels and anatomical structures.",
    features: [
      "Curved precision tip",
      "Facilitates vessel ligation",
      "Smooth tissue passage",
      "Reusable surgical steel",
    ],
    image: `${PRODUCT_IMAGE_BASE}/products/ligature-needle.png`,
    status: "Available",
  },
  {
    id: 63,
    name: "Lowmans Clamp",
    category: ["CS SETS", "ORTHO SETS"],
    description: "Lowman's clamp.",
    summary:
      "Orthopedic bone clamp used for grasping and stabilizing fractured bone segments.",
    features: [
      "Powerful gripping force",
      "Orthopedic fixation support",
      "Ratchet locking mechanism",
      "Heavy-duty construction",
    ],
    image: `${PRODUCT_IMAGE_BASE}/products/lowmans-clamp.png`,
    status: "Available",
  },
  {
    id: 64,
    name: "Malleable 1 5",
    category: ["CS SETS", "ORTHO SETS"],
    description: "Malleable instrument 1.5.",
    summary:
      "1.5-inch ribbon retractor that can be shaped to provide customized tissue retraction.",
    features: [
      "Flexible malleable blade",
      "Customizable surgical positioning",
      "Ideal for narrow fields",
      "Reusable stainless steel",
    ],
    image: `${PRODUCT_IMAGE_BASE}/products/malleable-1-5.png`,
    status: "Available",
  },
  {
    id: 65,
    name: "Malleable 1",
    category: ["CS SETS", "ORTHO SETS"],
    description: "Malleable instrument 1.",
    summary:
      "1-inch ribbon retractor designed for retraction in very narrow surgical spaces.",
    features: [
      "Highly flexible design",
      "Compact blade width",
      "Precise tissue retraction",
      "Autoclavable construction",
    ],
    image: `${PRODUCT_IMAGE_BASE}/products/malleable-1.png`,
    status: "Available",
  },
  {
    id: 66,
    name: "Malleable 2",
    category: ["CS SETS", "ORTHO SETS"],
    description: "Malleable instrument 2.",
    summary:
      "2-inch malleable retractor suitable for moderate surgical exposure and tissue protection.",
    features: [
      "Bendable ribbon blade",
      "Moderate-width exposure",
      "Adaptable positioning",
      "Surgical-grade steel",
    ],
    image: `${PRODUCT_IMAGE_BASE}/products/malleable-2.png`,
    status: "Available",
  },
  {
    id: 67,
    name: "Malleable 3",
    category: ["CS SETS", "ORTHO SETS"],
    description: "Malleable instrument 3.",
    summary:
      "3-inch ribbon retractor used for broad tissue retraction and deep cavity exposure.",
    features: [
      "Wide malleable blade",
      "Large surgical field exposure",
      "Flexible custom shaping",
      "Reusable construction",
    ],
    image: `${PRODUCT_IMAGE_BASE}/products/malleable-3.png`,
    status: "Available",
  },
  {
    id: 68,
    name: "Mayo Curve 6 5",
    category: ["CS SETS", "ORTHO SETS"],
    description: "Mayo curve 6.5.",
    summary:
      "Curved Mayo scissors designed for cutting dense tissue during surgical procedures.",
    features: [
      "Curved heavy-duty blades",
      "Excellent cutting strength",
      "Suitable for fascia and muscle",
      "Stainless steel construction",
    ],
    image: `${PRODUCT_IMAGE_BASE}/products/mayo-curve-6-5.png`,
    status: "Available",
  },
  {
    id: 69,
    name: "Mayo Scissors Curve 6",
    category: ["CS SETS", "ORTHO SETS"],
    description: "Mayo scissors curve 6.",
    summary:
      "6-inch curved Mayo scissors for cutting dense tissue and performing blunt dissection.",
    features: [
      "Curved surgical blades",
      "Heavy tissue cutting",
      "Durable cutting edges",
      "Reusable stainless steel",
    ],
    image: `${PRODUCT_IMAGE_BASE}/products/mayo-scissors-curve-6.png`,
    status: "Available",
  },
  {
    id: 70,
    name: "Mayo Scissors Curve 7",
    category: ["CS SETS", "ORTHO SETS"],
    description: "Mayo scissors curve 7.",
    summary:
      "7-inch curved Mayo scissors offering extended reach for cutting dense tissue structures.",
    features: [
      "Extended blade length",
      "Strong cutting performance",
      "Curved dissection profile",
      "Medical-grade steel",
    ],
    image: `${PRODUCT_IMAGE_BASE}/products/mayo-scissors-curve-7.png`,
    status: "Available",
  },
  {
    id: 71,
    name: "Mayo Scissors Curve 8",
    category: ["CS SETS", "ORTHO SETS"],
    description: "Mayo scissors curve 8.",
    summary:
      "8-inch Mayo scissors designed for deep surgical dissection and tissue cutting.",
    features: [
      "Long curved blades",
      "Excellent deep access",
      "Heavy-duty cutting action",
      "Reusable construction",
    ],
    image: `${PRODUCT_IMAGE_BASE}/products/mayo-scissors-curve-8.png`,
    status: "Available",
  },
  {
    id: 72,
    name: "Mayo Scissors Curve 9",
    category: ["CS SETS", "ORTHO SETS"],
    description: "Mayo scissors curve 9.",
    summary:
      "9-inch curved Mayo scissors providing maximum reach for deep operative fields.",
    features: [
      "Extra-long blade design",
      "Ideal for deep dissection",
      "High-strength cutting edges",
      "Corrosion-resistant finish",
    ],
    image: `${PRODUCT_IMAGE_BASE}/products/mayo-scissors-curve-9.png`,
    status: "Available",
  },
  {
    id: 73,
    name: "Mayo Scissors Straight 6 5",
    category: ["CS SETS", "ORTHO SETS"],
    description: "Mayo scissors straight 6.5.",
    summary:
      "Straight Mayo scissors used for cutting sutures, dressings, and dense tissue structures.",
    features: [
      "Straight precision blades",
      "Multi-purpose surgical use",
      "Strong cutting performance",
      "Reusable stainless steel",
    ],
    image: `${PRODUCT_IMAGE_BASE}/products/mayo-scissors-straight-6-5.png`,
    status: "Available",
  },
  {
    id: 74,
    name: "Mayo Scissors Straight 6",
    category: ["CS SETS", "ORTHO SETS"],
    description: "Mayo scissors straight 6.",
    summary:
      "6-inch straight Mayo scissors suitable for cutting sutures and surgical materials.",
    features: [
      "Straight blade profile",
      "Precise cutting action",
      "Balanced surgical handling",
      "Durable steel construction",
    ],
    image: `${PRODUCT_IMAGE_BASE}/products/mayo-scissors-straight-6.png`,
    status: "Available",
  },
  {
    id: 76,
    name: "Mayo Suture Scissors",
    category: ["CS SETS", "ORTHO SETS"],
    description: "Mayo suture scissors.",
    summary:
      "Specialized Mayo scissors designed for efficient cutting and removal of surgical sutures.",
    features: [
      "Sharp precision blades",
      "Optimized for suture removal",
      "Comfortable finger rings",
      "Reusable stainless steel construction",
    ],
    image: `${PRODUCT_IMAGE_BASE}/products/mayo-suture-scissors.png`,
    status: "Available",
  },
  {
    id: 77,
    name: "Metzenbaum 6",
    category: ["CS SETS", "ORTHO SETS"],
    description: "Metzenbaum scissors 6.",
    summary:
      "6-inch Metzenbaum scissors designed for delicate tissue dissection and precise cutting.",
    features: [
      "Fine tapered blades",
      "Ideal for delicate tissue work",
      "Lightweight surgical design",
      "Autoclavable stainless steel",
    ],
    image: `${PRODUCT_IMAGE_BASE}/products/metzenbaum-6.png`,
    status: "Available",
  },
  {
    id: 78,
    name: "Metzenbaum 7",
    category: ["CS SETS", "ORTHO SETS"],
    description: "Metzenbaum scissors 7.",
    summary:
      "7-inch Metzenbaum scissors providing additional reach for soft tissue dissection.",
    features: [
      "Extended blade length",
      "Precise tissue dissection",
      "Smooth cutting action",
      "Corrosion-resistant construction",
    ],
    image: `${PRODUCT_IMAGE_BASE}/products/metzenbaum-7.png`,
    status: "Available",
  },
  {
    id: 79,
    name: "Metzenbaum 9",
    category: ["CS SETS", "ORTHO SETS"],
    description: "Metzenbaum scissors 9.",
    summary:
      "9-inch Metzenbaum scissors for deep operative fields requiring delicate tissue handling.",
    features: [
      "Long precision blades",
      "Excellent deep access",
      "Fine tissue dissection",
      "Surgical-grade stainless steel",
    ],
    image: `${PRODUCT_IMAGE_BASE}/products/metzenbaum-9.png`,
    status: "Available",
  },
  {
    id: 80,
    name: "Metzenbaum",
    category: ["CS SETS", "ORTHO SETS"],
    description: "Metzenbaum scissors.",
    summary:
      "General-purpose Metzenbaum scissors used for delicate tissue cutting and blunt dissection.",
    features: [
      "Fine blade profile",
      "Delicate tissue handling",
      "Precision surgical performance",
      "Reusable construction",
    ],
    image: `${PRODUCT_IMAGE_BASE}/products/metzenbaum.png`,
    status: "Available",
  },
  {
    id: 81,
    name: "Mixter 6 Fine Tip",
    category: ["CS SETS", "ORTHO SETS"],
    description: "Mixter forceps 6 fine tip.",
    summary:
      "6-inch right-angle forceps with a fine tip for vessel dissection and ligature placement.",
    features: [
      "Fine right-angle jaws",
      "Precise vessel manipulation",
      "Ideal for ligature passing",
      "Ratchet locking mechanism",
    ],
    image: `${PRODUCT_IMAGE_BASE}/products/mixter-6-fine-tip.png`,
    status: "Available",
  },
  {
    id: 82,
    name: "Mixter 8 Dull Tip",
    category: ["CS SETS", "ORTHO SETS"],
    description: "Mixter forceps 8 dull tip.",
    summary:
      "8-inch Mixter forceps with blunt tips for atraumatic dissection and vessel isolation.",
    features: [
      "Blunt right-angle jaws",
      "Extended surgical reach",
      "Reduced tissue trauma",
      "Medical-grade stainless steel",
    ],
    image: `${PRODUCT_IMAGE_BASE}/products/mixter-8-dull-tip.png`,
    status: "Available",
  },
  {
    id: 83,
    name: "Mosquito Curved M",
    category: ["CS SETS", "ORTHO SETS"],
    description: "Mosquito curved (M).",
    summary:
      "Medium curved mosquito hemostat used for clamping small blood vessels and delicate tissues.",
    features: [
      "Curved serrated jaws",
      "Fine hemostatic control",
      "Compact surgical profile",
      "Reliable ratchet lock",
    ],
    image: `${PRODUCT_IMAGE_BASE}/products/mosquito-curved-m.png`,
    status: "Available",
  },
  {
    id: 84,
    name: "Mosquito Curved S",
    category: ["CS SETS", "ORTHO SETS"],
    description: "Mosquito curved (S).",
    summary:
      "Small curved mosquito forceps designed for precision hemostasis in confined surgical spaces.",
    features: [
      "Small curved jaws",
      "Precise vessel clamping",
      "Fine-tip design",
      "Reusable stainless steel",
    ],
    image: `${PRODUCT_IMAGE_BASE}/products/mosquito-curved-s.png`,
    status: "Available",
  },
  {
    id: 85,
    name: "Mosquito Curved",
    category: ["CS SETS", "ORTHO SETS"],
    description: "Mosquito curved.",
    summary:
      "Curved hemostatic forceps commonly used to control bleeding from small vessels.",
    features: [
      "Curved serrated jaws",
      "Secure vessel occlusion",
      "Ratchet locking handle",
      "Corrosion-resistant finish",
    ],
    image: `${PRODUCT_IMAGE_BASE}/products/mosquito-curved.png`,
    status: "Available",
  },
  {
    id: 86,
    name: "Mosquito Straight",
    category: ["CS SETS", "ORTHO SETS"],
    description: "Mosquito straight.",
    summary:
      "Straight mosquito forceps used for clamping small vessels and delicate tissue structures.",
    features: [
      "Straight precision jaws",
      "Excellent hemostatic control",
      "Fine-tip design",
      "Reusable surgical steel",
    ],
    image: `${PRODUCT_IMAGE_BASE}/products/mosquito-straight.png`,
    status: "Available",
  },
  {
    id: 87,
    name: "Mouth Retractor",
    category: ["CS SETS", "ORTHO SETS"],
    description: "Mouth retractor.",
    summary:
      "Retractor used to hold the mouth open and provide clear access during oral procedures.",
    features: [
      "Enhanced oral cavity exposure",
      "Comfortable retraction design",
      "Suitable for dental and ENT use",
      "Durable stainless steel",
    ],
    image: `${PRODUCT_IMAGE_BASE}/products/mouth-retractor.png`,
    status: "Available",
  },
  {
    id: 88,
    name: "Nasal Speculum",
    category: ["CS SETS", "ORTHO SETS"],
    description: "Nasal speculum.",
    summary:
      "ENT instrument used to widen the nostrils for examination and surgical access.",
    features: [
      "Adjustable opening blades",
      "Improved nasal visualization",
      "Smooth atraumatic edges",
      "Reusable construction",
    ],
    image: `${PRODUCT_IMAGE_BASE}/products/nasal-speculum.png`,
    status: "Available",
  },
  {
    id: 89,
    name: "Needle Holder 5",
    category: ["CS SETS", "ORTHO SETS"],
    description: "Needle holder 5.",
    summary:
      "5-inch needle holder designed for precise handling of surgical needles during suturing.",
    features: [
      "Short precision profile",
      "Secure needle grip",
      "Ratchet locking mechanism",
      "Surgical-grade stainless steel",
    ],
    image: `${PRODUCT_IMAGE_BASE}/products/needle-holder-5.png`,
    status: "Available",
  },
  {
    id: 90,
    name: "Needle Holder 6",
    category: ["CS SETS", "ORTHO SETS"],
    description: "Needle holder 6.",
    summary:
      "6-inch needle holder offering balanced control for routine suturing procedures.",
    features: [
      "Precision jaw alignment",
      "Secure needle retention",
      "Comfortable handling",
      "Reusable construction",
    ],
    image: `${PRODUCT_IMAGE_BASE}/products/needle-holder-6.png`,
    status: "Available",
  },
  {
    id: 91,
    name: "Needle Holder 8",
    category: ["CS SETS", "ORTHO SETS"],
    description: "Needle holder 8.",
    summary:
      "8-inch needle holder providing extended reach for deep surgical closures.",
    features: [
      "Long surgical reach",
      "Firm needle grip",
      "Ratchet locking system",
      "Corrosion-resistant steel",
    ],
    image: `${PRODUCT_IMAGE_BASE}/products/needle-holder-8.png`,
    status: "Available",
  },
  {
    id: 92,
    name: "Needle Holder Tracheostomy",
    category: ["CS SETS", "ORTHO SETS"],
    description: "Needle holder (tracheostomy).",
    summary:
      "Specialized needle holder optimized for suturing during tracheostomy procedures.",
    features: [
      "Designed for airway surgery",
      "Precise needle control",
      "Secure locking mechanism",
      "Medical-grade stainless steel",
    ],
    image: `${PRODUCT_IMAGE_BASE}/products/needle-holder-tracheostomy.png`,
    status: "Available",
  },
  {
    id: 93,
    name: "Needle Holder",
    category: ["CS SETS", "ORTHO SETS"],
    description: "Needle holder.",
    summary:
      "General-purpose surgical needle holder for controlled suturing and wound closure.",
    features: [
      "Precision needle handling",
      "Secure jaw grip",
      "Ergonomic ring handles",
      "Reusable surgical steel",
    ],
    image: `${PRODUCT_IMAGE_BASE}/products/needle-holder.png`,
    status: "Available",
  },
  {
    id: 94,
    name: "Ochsner Cu 9 5",
    category: ["CS SETS", "ORTHO SETS"],
    description: "Ochsner cu 9.5.",
    summary:
      "9.5-inch curved Ochsner forceps used for grasping dense tissue and fascia.",
    features: [
      "Curved serrated jaws with teeth",
      "Strong tissue grip",
      "Extended surgical reach",
      "Ratchet locking handle",
    ],
    image: `${PRODUCT_IMAGE_BASE}/products/ochsner-cu-9-5.png`,
    status: "Available",
  },
  {
    id: 95,
    name: "Ochsner St 6",
    category: ["CS SETS", "ORTHO SETS"],
    description: "Ochsner st 6.",
    summary:
      "6-inch straight Ochsner forceps for securely grasping tough tissue structures.",
    features: [
      "Straight toothed jaws",
      "Strong holding capability",
      "Secure locking ratchet",
      "Durable stainless steel",
    ],
    image: `${PRODUCT_IMAGE_BASE}/products/ochsner-st-6.png`,
    status: "Available",
  },
  {
    id: 96,
    name: "Ochsner St 7",
    category: ["CS SETS", "ORTHO SETS"],
    description: "Ochsner st 7.",
    summary:
      "7-inch straight Ochsner forceps providing additional reach and secure tissue fixation.",
    features: [
      "Extended straight jaws",
      "Toothed gripping surface",
      "Reliable tissue retention",
      "Reusable construction",
    ],
    image: `${PRODUCT_IMAGE_BASE}/products/ochsner-st-7.png`,
    status: "Available",
  },
  {
    id: 97,
    name: "Ovum Forceps Curved",
    category: ["CS SETS", "ORTHO SETS"],
    description: "Ovum forceps curved.",
    summary:
      "Curved ovum forceps used in gynecological procedures for tissue and product retrieval.",
    features: [
      "Curved fenestrated jaws",
      "Atraumatic tissue handling",
      "Extended surgical reach",
      "Medical-grade stainless steel",
    ],
    image: `${PRODUCT_IMAGE_BASE}/products/ovum-forceps-curved.png`,
    status: "Available",
  },
  {
    id: 98,
    name: "Ovum Forceps D And C",
    category: ["CS SETS", "ORTHO SETS"],
    description: "Ovum forceps (D&C).",
    summary:
      "Ovum forceps designed specifically for dilation and curettage procedures.",
    features: [
      "Gynecological procedure optimized",
      "Fenestrated atraumatic jaws",
      "Secure tissue retrieval",
      "Reusable surgical steel",
    ],
    image: `${PRODUCT_IMAGE_BASE}/products/ovum-forceps-d-and-c.png`,
    status: "Available",
  },
  {
    id: 99,
    name: "Ovum Forceps Straight",
    category: ["CS SETS", "ORTHO SETS"],
    description: "Ovum forceps straight.",
    summary:
      "Straight ovum forceps used for uterine tissue handling and retrieval procedures.",
    features: [
      "Straight fenestrated jaws",
      "Controlled tissue grasping",
      "Gynecological surgical use",
      "Corrosion-resistant finish",
    ],
    image: `${PRODUCT_IMAGE_BASE}/products/ovum-forceps-straight.png`,
    status: "Available",
  },
  {
    id: 100,
    name: "Ovum Forceps",
    category: ["CS SETS", "ORTHO SETS"],
    description: "Ovum forceps.",
    summary:
      "General-purpose ovum forceps used for grasping and removing tissue during gynecological procedures.",
    features: [
      "Atraumatic fenestrated jaws",
      "Secure tissue retrieval",
      "Long surgical reach",
      "Reusable stainless steel",
    ],
    image: `${PRODUCT_IMAGE_BASE}/products/ovum-forceps.png`,
    status: "Available",
  },
  {
    id: 101,
    name: "Pean Curved 6 1/4",
    category: ["CS SETS", "ORTHO SETS"],
    description: "Pean curved 6 1/4.",
    summary:
      "Curved Pean hemostatic forceps designed for clamping blood vessels and grasping tissue during surgery.",
    features: [
      "Curved serrated jaws",
      "Secure hemostatic control",
      "Ratchet locking mechanism",
      "Medical-grade stainless steel",
    ],
    image: `${PRODUCT_IMAGE_BASE}/products/pean-curved-6-1_4.png`,
    status: "Available",
  },
  {
    id: 102,
    name: "Pean Forceps Straight 8",
    category: ["CS SETS", "ORTHO SETS"],
    description: "Pean forceps straight 8.",
    summary:
      "8-inch straight Pean forceps providing strong clamping performance for vascular and tissue control.",
    features: [
      "Straight serrated jaws",
      "Extended surgical reach",
      "Reliable ratchet lock",
      "Corrosion-resistant steel",
    ],
    image: `${PRODUCT_IMAGE_BASE}/products/pean-forceps-straight-8.png`,
    status: "Available",
  },
  {
    id: 103,
    name: "Pean Straight 6",
    category: ["CS SETS", "ORTHO SETS"],
    description: "Pean straight 6.",
    summary:
      "Straight hemostatic forceps used for vessel occlusion, tissue handling, and surgical dissection.",
    features: [
      "Straight clamping jaws",
      "Strong hemostatic grip",
      "Precision surgical control",
      "Reusable stainless steel",
    ],
    image: `${PRODUCT_IMAGE_BASE}/products/pean-forceps-straight-6.png`,
    status: "Available",
  },
  {
    id: 104,
    name: "Tissue Forceps 5.5",
    category: ["CS SETS", "ORTHO SETS"],
    description: "Tissue forceps 5.5.",
    summary:
      "Fine tissue forceps with a 5.5 jaw configuration for precise grasping and handling of delicate tissue during surgical procedures.",
    features: [
      "Fine 5.5 jaw configuration",
      "Secure tissue grasping",
      "Precise surgical control",
      "Reusable stainless steel",
    ],
    image: `${PRODUCT_IMAGE_BASE}/products/tissue-forceps-5-5.png`,
    status: "Available",
  },
  {
    id: 105,
    name: "Poole Suction",
    category: ["CS SETS", "ORTHO SETS"],
    description: "Poole suction.",
    summary:
      "Suction instrument designed for rapid removal of fluids from large surgical cavities.",
    features: [
      "Multi-perforated suction tip",
      "High-volume fluid evacuation",
      "Ideal for abdominal surgery",
      "Autoclavable construction",
    ],
    image: `${PRODUCT_IMAGE_BASE}/products/poole-suction.png`,
    status: "Available",
  },
  {
    id: 106,
    name: "Pyer Forcep",
    category: ["CS SETS", "ORTHO SETS"],
    description: "Pyer forcep.",
    summary:
      "Specialized forceps used for grasping and manipulating tissue during surgical procedures.",
    features: [
      "Precision jaw alignment",
      "Secure gripping action",
      "Ergonomic finger rings",
      "Reusable surgical steel",
    ],
    image: `${PRODUCT_IMAGE_BASE}/products/pyer-forcep.png`,
    status: "Available",
  },
  {
    id: 107,
    name: "Rake Retractor B",
    category: ["CS SETS", "ORTHO SETS"],
    description: "Rake retractor (B).",
    summary:
      "Large rake retractor used for separating soft tissue and improving surgical exposure.",
    features: [
      "Multi-prong rake design",
      "Strong tissue retraction",
      "Excellent wound exposure",
      "Stainless steel construction",
    ],
    image: `${PRODUCT_IMAGE_BASE}/products/rake-retractor-blunt.png`,
    status: "Available",
  },
  {
    id: 108,
    name: "Rake Retractor M",
    category: ["CS SETS", "ORTHO SETS"],
    description: "Rake retractor (M).",
    summary:
      "Medium-sized rake retractor designed for controlled soft tissue retraction.",
    features: [
      "Multiple sharp prongs",
      "Enhanced surgical visibility",
      "Balanced ergonomic handle",
      "Reusable construction",
    ],
    image: `${PRODUCT_IMAGE_BASE}/products/rake-retractor-sharp.png`,
    status: "Available",
  },
  {
    id: 109,
    name: "Randall",
    category: ["CS SETS", "ORTHO SETS"],
    description: "Randall forceps.",
    summary:
      "Stone forceps commonly used in urological procedures for retrieving calculi and foreign bodies.",
    features: [
      "Long slender shaft",
      "Secure retrieval jaws",
      "Urological procedure support",
      "Medical-grade stainless steel",
    ],
    image: `${PRODUCT_IMAGE_BASE}/products/randall.png`,
    status: "Available",
  },
  {
    id: 110,
    name: "Rib Retractor",
    category: ["CS SETS", "ORTHO SETS"],
    description: "Rib retractor.",
    summary:
      "Thoracic surgical retractor used to separate ribs and maintain chest cavity access.",
    features: [
      "Heavy-duty retraction system",
      "Adjustable opening mechanism",
      "Excellent thoracic exposure",
      "Durable surgical-grade steel",
    ],
    image: `${PRODUCT_IMAGE_BASE}/products/rib-retractor.png`,
    status: "Available",
  },
  {
    id: 111,
    name: "Richardson Eastman Retractor",
    category: ["CS SETS", "ORTHO SETS"],
    description: "Richardson-Eastman retractor.",
    summary:
      "Double-ended retractor used for deep wound exposure and soft tissue retraction.",
    features: [
      "Dual-ended blade design",
      "Deep surgical access",
      "Strong retraction capability",
      "Reusable stainless steel",
    ],
    image: `${PRODUCT_IMAGE_BASE}/products/richardson-double-ended.png`,
    status: "Available",
  },
  {
    id: 112,
    name: "Richardson Retractor",
    category: ["CS SETS", "ORTHO SETS"],
    description: "Richardson retractor.",
    summary:
      "Handheld retractor designed for retracting wound edges and soft tissue during surgery.",
    features: [
      "Right-angled blade",
      "Excellent tissue exposure",
      "Comfortable grip handle",
      "Corrosion-resistant finish",
    ],
    image: `${PRODUCT_IMAGE_BASE}/products/richardson-m.png`,
    status: "Available",
  },
  {
    id: 113,
    name: "Screw Driver",
    category: ["ORTHO SETS", "NEW SETS"],
    description:
      "Orthopedic screw driver used for insertion and removal of bone screws during fixation procedures.",
    summary:
      "Precision orthopedic screwdriver designed for driving, tightening, and removing surgical bone screws during trauma and reconstructive procedures.",
    features: [
      "Precision-machined screwdriver tip",
      "Compatible with orthopedic bone screws",
      "Provides controlled torque and stability",
      "Ergonomic handle for secure grip",
      "Medical-grade stainless steel construction",
      "Reusable and fully autoclavable",
    ],
    image: `${PRODUCT_IMAGE_BASE}/products/screw-driver.png`,
    status: "Available",
  },
  {
    id: 115,
    name: "Senn Miller Retractor",
    category: ["CS SETS", "ORTHO SETS"],
    description: "Senn-Miller retractor.",
    summary:
      "Double-ended retractor used in plastic, orthopedic, and general surgical procedures.",
    features: [
      "Rake and blade combination",
      "Ideal for superficial tissues",
      "Compact surgical profile",
      "Autoclavable stainless steel",
    ],
    image: `${PRODUCT_IMAGE_BASE}/products/senn-miller-retractor.png`,
    status: "Available",
  },
  {
    id: 116,
    name: "Sharp Curette 0 0",
    category: ["CS SETS", "ORTHO SETS"],
    description: "Sharp curette #0.0.",
    summary:
      "Sharp curette used for precise scraping and removal of tissue during gynecological procedures.",
    features: [
      "Sharp curetting edge",
      "Controlled tissue removal",
      "Fine surgical precision",
      "Reusable stainless steel",
    ],
    image: `${PRODUCT_IMAGE_BASE}/products/sharp-curette-0.0.png`,
    status: "Available",
  },
  {
    id: 117,
    name: "Sharp Curette 0",
    category: ["CS SETS", "ORTHO SETS"],
    description: "Sharp curette size 0.",
    summary:
      "Small sharp curette used for precise scraping, debridement, and removal of soft tissue during gynecological and surgical procedures.",
    features: [
      "Sharp curette tip for precise tissue removal",
      "Size 0 for delicate procedures",
      "Excellent tactile control",
      "Medical-grade stainless steel construction",
    ],
    image: `${PRODUCT_IMAGE_BASE}/products/sharp-curette-0.png`,
    status: "Available",
  },
  {
    id: 118,
    name: "Sharp Curette 2",
    category: ["CS SETS", "ORTHO SETS"],
    description: "Sharp curette size 2.",
    summary:
      "Medium-sized sharp curette designed for controlled tissue scraping and curettage procedures.",
    features: [
      "Sharp cutting edge for effective curettage",
      "Size 2 working end",
      "Suitable for gynecological and surgical applications",
      "Reusable stainless steel instrument",
    ],
    image: `${PRODUCT_IMAGE_BASE}/products/sharp-curette-2.png`,
    status: "Available",
  },
  {
    id: 119,
    name: "Sharp Curette 5",
    category: ["CS SETS", "ORTHO SETS"],
    description: "Sharp curette size 5.",
    summary:
      "Large sharp curette used for efficient tissue removal, debridement, and curettage in surgical procedures.",
    features: [
      "Larger curette head for greater tissue coverage",
      "Sharp edge for effective scraping",
      "Designed for controlled tissue removal",
      "Durable surgical-grade stainless steel",
    ],
    image: `${PRODUCT_IMAGE_BASE}/products/sharp-curette-5.png`,
    status: "Available",
  },
  {
    id: 120,
    name: "Suction Tip",
    category: ["CS SETS", "ORTHO SETS"],
    description: "Suction tip.",
    summary:
      "Surgical suction tip used to remove blood, fluids, and debris while maintaining a clear operative field.",
    features: [
      "Efficient fluid aspiration",
      "Precision suction control",
      "Smooth tip design for atraumatic use",
      "Reusable and autoclavable stainless steel construction",
    ],
    image: `${PRODUCT_IMAGE_BASE}/products/suction-tip.png`,
    status: "Available",
  },
  {
    id: 121,
    name: "Tenaculum",
    category: ["CS SETS", "ORTHO SETS"],
    description: "Tenaculum.",
    summary:
      "Sharp-hooked gynecological forceps used to grasp and stabilize the cervix during procedures.",
    features: [
      "Sharp opposing hooks",
      "Secure cervical traction",
      "Precise tissue control",
      "Medical-grade stainless steel",
    ],
    image: `${PRODUCT_IMAGE_BASE}/products/tenaculum.png`,
    status: "Available",
  },
  {
    id: 122,
    name: "Tissue Forceps C Teeth",
    category: ["CS SETS", "ORTHO SETS"],
    description: "Tissue forceps with C teeth.",
    summary:
      "Toothed tissue forceps designed for secure grasping of skin and dense tissue.",
    features: [
      "Interlocking toothed tips",
      "Firm tissue grip",
      "Precision surgical handling",
      "Reusable stainless steel",
    ],
    image: `${PRODUCT_IMAGE_BASE}/products/tissue-forceps-c-teeth.png`,
    status: "Available",
  },
  {
    id: 123,
    name: "Tissue Forceps S Teeth",
    category: ["CS SETS", "ORTHO SETS"],
    description: "Tissue forceps with S teeth.",
    summary:
      "Serrated tissue forceps used for controlled manipulation of tissue during surgical procedures.",
    features: [
      "Serrated gripping surface",
      "Reliable tissue handling",
      "Lightweight ergonomic design",
      "Corrosion-resistant finish",
    ],
    image: `${PRODUCT_IMAGE_BASE}/products/tissue-forceps-s-teeth.png`,
    status: "Available",
  },
  {
    id: 124,
    name: "Trachea Bistoury Curved Blade",
    category: ["CS SETS", "ORTHO SETS"],
    description: "Trachea bistoury curved blade.",
    summary:
      "Specialized tracheostomy instrument combining a curved blade and probe for controlled tracheal incision.",
    features: [
      "Integrated probe guidance",
      "Curved precision blade",
      "Optimized for tracheostomy",
      "Reusable surgical-grade steel",
    ],
    image: `${PRODUCT_IMAGE_BASE}/products/trachea-bistori-curblade-c-probe.png`,
    status: "Available",
  },
  {
    id: 125,
    name: "Vaginal Ret",
    category: ["CS SETS", "ORTHO SETS"],
    description: "Vaginal ret.",
    summary:
      "Gynecological retractor used to expose the vaginal canal and cervix during examination and surgery.",
    features: [
      "Enhanced vaginal exposure",
      "Smooth atraumatic blade",
      "Comfortable surgical handling",
      "Autoclavable stainless steel",
    ],
    image: `${PRODUCT_IMAGE_BASE}/products/vaginal-ret.png`,
    status: "Available",
  },
  {
    id: 126,
    name: "Bone Curette",
    category: ["CS SETS", "ORTHO SETS"],
    description: "Bone curette.",
    summary:
      "Orthopedic curette designed for scraping bone cavities, removing pathological tissue, and debriding bone surfaces.",
    features: [
      "Sharp spoon-shaped curette tip",
      "Effective bone debridement",
      "Precision orthopedic application",
      "Reusable stainless steel construction",
    ],
    image: `${PRODUCT_IMAGE_BASE}/products/bone-curette.png`,
    status: "Available",
  },
  {
    id: 127,
    name: "Weitlaner Retractor",
    category: ["CS SETS", "ORTHO SETS"],
    description: "Weitlaner retractor.",
    summary:
      "Handheld rake retractor used for retracting skin, fascia, and superficial tissue during surgery.",
    features: [
      "Multiple sharp prongs",
      "Excellent superficial tissue retraction",
      "Ergonomic handle design",
      "Medical-grade stainless steel",
    ],
    image: `${PRODUCT_IMAGE_BASE}/products/weitlaner-retractor.png`,
    status: "Available",
  },
  {
    id: 128,
    name: "Wire Cutter Scissor",
    category: ["CS SETS", "ORTHO SETS"],
    description: "Wire cutter scissor.",
    summary:
      "Orthopedic cutting instrument designed for trimming surgical wires, pins, and fixation materials.",
    features: [
      "High-strength cutting jaws",
      "Clean wire cutting performance",
      "Orthopedic surgical use",
      "Durable stainless steel construction",
    ],
    image: `${PRODUCT_IMAGE_BASE}/products/wire-cutter-scissor.png`,
    status: "Available",
  },
  {
    id: 129,
    name: "Suction Tip",
    category: ["CS SETS", "ORTHO SETS"],
    description: "Suction tip.",
    summary:
      "Rigid suction instrument used for removing fluids and maintaining a clear surgical field.",
    features: [
      "Bulbous atraumatic tip",
      "Efficient fluid evacuation",
      "Excellent suction control",
      "Autoclavable stainless steel",
    ],
    image: `${PRODUCT_IMAGE_BASE}/products/suction-tip.png`,
    status: "Available",
  },
  {
    id: 130,
    name: "Adson Thumb Forcep",
    category: ["CUTDOWN SETS", "NEW SETS"],
    description: "Adson thumb forcep.",
    summary:
      "Fine thumb forceps included in cutdown sets for handling delicate tissue and dressings during vascular access procedures.",
    features: [
      "Fine serrated tips",
      "Ideal for delicate tissue handling",
      "Lightweight ergonomic profile",
      "Reusable surgical-grade steel",
    ],
    image: `${PRODUCT_IMAGE_BASE}/products/adson-thumb-forcep.png`,
    status: "Available",
  },
  {
    id: 131,
    name: "Allis Forceps",
    category: ["CUTDOWN SETS", "NEW SETS"],
    description: "Allis forceps.",
    summary:
      "Allis tissue forceps used in cutdown procedures for securely grasping fascia and soft tissue.",
    features: [
      "Interlocking tissue-holding teeth",
      "Ratchet locking mechanism",
      "Secure tissue traction",
      "Medical-grade stainless steel",
    ],
    image: `${PRODUCT_IMAGE_BASE}/products/allis-6.png`,
    status: "Available",
  },
  {
    id: 132,
    name: "Dissecting Scissors",
    category: ["CUTDOWN SETS", "NEW SETS"],
    description: "Dissecting scissors.",
    summary:
      "Precision dissecting scissors used in cutdown procedures for tissue separation and controlled cutting.",
    features: [
      "Sharp precision blades",
      "Smooth dissection capability",
      "Fine tissue handling",
      "Reusable stainless steel construction",
    ],
    image: `${PRODUCT_IMAGE_BASE}/products/dissecting-scissors.png`,
    status: "Available",
  },
  {
    id: 133,
    name: "Iris Scissors Curved",
    category: ["CUTDOWN SETS", "NEW SETS"],
    description: "Iris scissors curved.",
    summary:
      "Fine curved iris scissors used for delicate dissection and precision cutting in cutdown procedures.",
    features: [
      "Curved precision blades",
      "Excellent maneuverability",
      "Suitable for delicate tissue work",
      "Autoclavable stainless steel",
    ],
    image: `${PRODUCT_IMAGE_BASE}/products/iris-scissor-curved.png`,
    status: "Available",
  },
  {
    id: 134,
    name: "Iris Scissors Straight",
    category: ["CUTDOWN SETS", "NEW SETS"],
    description: "Iris scissors straight.",
    summary:
      "Straight iris scissors designed for precision cutting and fine tissue work during cutdown procedures.",
    features: [
      "Straight micro-dissection blades",
      "Fine surgical precision",
      "Ideal for detailed procedures",
      "Corrosion-resistant finish",
    ],
    image: `${PRODUCT_IMAGE_BASE}/products/iris-scissor-straight.png`,
    status: "Available",
  },
  {
    id: 135,
    name: "Senn Miller Retractor",
    category: ["CUTDOWN SETS", "NEW SETS"],
    description: "Senn-Miller retractor.",
    summary:
      "Double-ended retractor included in cutdown sets for exposing superficial tissues and small operative sites.",
    features: [
      "Rake and blade combination",
      "Ideal for superficial exposure",
      "Compact surgical profile",
      "Reusable stainless steel",
    ],
    image: `${PRODUCT_IMAGE_BASE}/products/senn-miller-retractor.png`,
    status: "Available",
  },
  {
    id: 136,
    name: "Metzenbaum Scissors",
    category: ["MINOR SETS", "NEW SETS"],
    description: "Metzenbaum scissors.",
    summary:
      "Metzenbaum scissors used in minor surgical procedures for delicate tissue dissection and cutting.",
    features: [
      "Fine tapered blades",
      "Excellent soft tissue dissection",
      "Precision surgical control",
      "Medical-grade stainless steel",
    ],
    image: `${PRODUCT_IMAGE_BASE}/products/metzenbaum.png`,
    status: "Available",
  },
  {
    id: 137,
    name: "Mayo Scissors",
    category: ["MINOR SETS", "NEW SETS"],
    description: "Mayo scissors.",
    summary:
      "General-purpose Mayo scissors included in minor surgical sets for cutting tissue, sutures, and dressings.",
    features: [
      "Heavy-duty cutting blades",
      "Versatile surgical application",
      "Balanced ergonomic design",
      "Autoclavable stainless steel construction",
    ],
    image: `${PRODUCT_IMAGE_BASE}/products/mayo-scissors.png`,
    status: "Available",
  },
].sort((a, b) => a.name.localeCompare(b.name));

export default products;
